(specifications->manifest
 '("fontconfig"
   "font-adobe-source-code-pro"
   "openconnect"
   "cifs-utils"
   "nfs-utils"
   "samba"
   "freerdp"
   ;; "sdl2"
   ;; "libffi"
   ;; "sbcl-cffi-libffi"
   "emacs"
   "emacs-exwm"
   "emacs-pdf-tools"
   "mu"
   "offlineimap"
   "msmtp"
   "libnotify"
   "texlive"
   "sbcl"
   "webkitgtk"
   "glib-networking"
   "gsettings-desktop-schemas"
   "gstreamer"
   "gst-plugins-base"
   "gst-plugins-good"
   "gst-plugins-bad"
   "gst-plugins-ugly"
   "r-openssl"
   "sqlite"
   "sbcl-cl-sqlite"
   "libfixposix"
   "sbcl-next"
   "cairo"
   "global"
   "icecat"
   "arandr"
   "guile"))
