(specifications->manifest
 '("fontconfig"
   "font-adobe-source-code-pro"
   "xset"
   "font-google-noto"
   "openconnect"
   "python"
   "python-pip"
   "python-matplotlib"
   "python-numpy"
   "python-distro"
   "python-kivy"
   "cifs-utils"
   "nfs-utils"
   "openssh"
   "sshfs"
   "samba"
   "freerdp"
   "htop"
   "mpv"
   "emacs-telega"
   "lua"
   "lxqt-themes"
   "kiconthemes"
   "wine"
   ;; "syncthing"
   "texlive"
   "aspell"
   "gnupg"
   "password-store"
   "ripgrep"
   "mesa-utils"
   "msmtp"
   "emacs-bluetooth"
   "blueman"
   "libnotify"
   "sbcl"
   "libffi"
   "lapack"
   "openblas"
   ;; "sbcl-py4cl"
   "cl-py4cl"
   "xdotool"
   "rsync"
   "libreoffice"
   "webkitgtk"
   "glib-networking"
   "gsettings-desktop-schemas"
   "gstreamer"
   "gst-plugins-base"
   "gst-plugins-good"
   ;; "gst-plugins-bad"
   "gst-plugins-ugly"
   "r-openssl"
   "sqlite"
   "sbcl-cl-sqlite"
   "libfixposix"
   "cairo"
   "global"
   "pavucontrol"
   ;; "firefox"
   "pdfpc"
   ;; "zathura"
   ;; "zathura-pdf-poppler"
   "emacs-pdf-tools"
   "mupdf"
   "arandr"
   ;; "tensorflow"
   "termite"
   "xournal"
   ;; "plover"
   "ghc-tldr"
   "lm-sensors"
   "inkscape"
   "flatpak"
   "obs"
   "q5go"
   "leela-zero"
   "gfortran-toolchain"
   "libgccjit"
   "mpich"
   "openmpi"))
