(specifications->manifest
 '("fontconfig"
   "font-adobe-source-code-pro"
   "make"
   "cmake"
   "xset"
   "xdpyinfo"
   "xprop"
   ;; "emacs-native-comp"
   "xlsfonts"
   "font-google-noto"
   "font-iosevka"
   "font-fira-code"
   "font-fira-mono"
   "font-fira-sans"
   "openconnect"
   "fish"                               ; for emacs completion support
   "vim"
   ;; "guile-ncurses"
   "ncurses"
   "octave"
   "python"
   ;; "python-pip"
   ;; "python-matplotlib"
   ;; "python-numpy"
   "python-sympy"
   "python-distro"
   "python-kivy"
   ;; "python-pyqt"
   ;; "python-sip"                         ; TODO really needed?
   ;; "python-dbus"
   ;; "wmctrl"
   ;; "python-qtconsole"
   ;; "python-pyqtwebengine"
   ;; "aria2"
   ;; "qtmultimedia"
   "gsl"
   "cifs-utils"
   "nfs-utils"
   "openssh"
   "sshfs"
   "samba"
   "freerdp"
   "htop"
   "ffmpeg"
   "mpv"
   "gimp"
   "emacs-telega"
   ;; "emacs-sly"
   "lua"
   "lxqt-themes"
   "kiconthemes"
   "wine"
   ;; "syncthing"
   "texlive"
   "aspell"
   "aspell-dict-en"
   "gnupg"
   "password-store"
   "ripgrep"
   "fd"
   "shellcheck"
   "mesa-utils"
   "msmtp"
   "notmuch"
   "emacs-bluetooth"
   "blueman"
   "libnotify"
   "libffi"
   "lapack"
   "openblas"
   ;; "sbcl-py4cl"
   "scrot"
   "gparted"
   "xdotool"
   "rsync"
   "libreoffice"
   "unoconv"
   "webkitgtk"
   "glib-networking"
   "gsettings-desktop-schemas"
   "gstreamer"
   "gst-plugins-base"
   "gst-plugins-good"
   ;; "gst-plugins-bad"
   "gst-plugins-ugly"
   "r-openssl"
   "sqlite"
   "sbcl-cl-sqlite"
   "libfixposix"
   "cairo"
   "global"
   "pulseaudio"
   "pavucontrol"
   "paprefs"
   ;; "firefox"
   "nyxt"
   "pdfpc"
   "imagemagick"
   "ghostscript"
   "mercurial"
   "ungoogled-chromium"
   "pcmanfm"
   ;; "zathura"
   ;; "zathura-pdf-poppler"
   "poppler"
   "emacs-pdf-tools"
   "mupdf"
   "arandr"
   ;; "tensorflow"
   "setxkbmap"
   "xcape"
   "termite"
   ;; "dmenu"
   "rofi"
   "xournal"
   "handbrake"
   ;; "plover"
   "ghc-tldr"
   "lm-sensors"
   "wordnet"
   "inkscape"
   "flatpak"
   ;; "obs"
   ;; "steam"
   "q5go"
   "leela-zero"
   "gfortran-toolchain"
   "libgccjit"
   "mpich"
   "openmpi"
   ;; qmk keyboard stuff
   ;; "arm-none-eabi-toolchain"
   ;; "avr-toolchain@4.9.4"
   ;; "avrdude"
   ;; "dfu-programmer"
   ;; "dfu-util"
   ))
