#! /bin/sh

gap=5
PANEL_HEIGHT=29
export gap
export PANEL_HEIGHT
#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

##Color settings
bspc config focused_border_color "#00ADEE"
bspc config normal_border_color "#2D2D2D"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 2

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting
sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
workspaces_multimonitor &
bspc config remove_disabled_monitor true
bspc config remove_unplugged_monitors true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled 
bspc rule -a plasmashell state=floating 
