# Do not modify this file!  It was generated by 'nixos-generate-config'
# and will be overwritten by future invocations.
#
# This file contains the hardware configuration for your system.
# You MUST run 'nixos-generate-config' after installation to populate
# this file with your actual hardware configuration.
#
# This is a placeholder template - replace with actual generated config

{config, lib, pkgs, modulesPath, ...}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Filesystems - UPDATE THESE WITH ACTUAL UUIDs
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "btrfs";
    options = ["subvol=@log" "compress=zstd" "noatime"];
  };

  fileSystems."/var/cache/pacman/pkg" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "btrfs";
    options = ["subvol=@pkg" "compress=zstd" "noatime"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "btrfs";
    options = ["subvol=@.snapshots" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # Zram swap
  zramSwap = {
    enable = true;
    memoryPercent = 50; # 4GB on 8GB system
  };

  # CPU
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Network
  networking.useDHCP = lib.mkDefault true;
}