#!/bin/bash

# mono ~/BoSSS-experimental/internal/src/private-kli/BoSSSpad-console-simple/BoSSSpad-console-simple/bin/Debug/BoSSSpad-console-simple.exe
mono ~/BoSSS-experimental/public/src/L4-application/BoSSSpad/bin/Debug/BoSSSpad.exe --simpleconsole
# mono ~/BoSSS-experimental/public/src/L4-application/BoSSSpad/bin/Debug/BoSSSpad.exe --console
