#!/bin/bash

xrandr --output LVDS1 --auto --primary --output VGA1 --off
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Finger") LVDS1xrandr --output LVDS1 --auto --right-of VGA1 --primary
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Pen Pen (0)") LVDS1
nitrogen --head=0 ~/.config/backgrounds/current/ --random --set-auto 
killall conky
conky --quiet &
