#!/bin/bash

xrandr --output LVDS1 --auto --below VGA1 --primary --output VGA1 --auto
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Finger") LVDS1
xinput --map-to-output $(xinput list --id-only "Wacom ISDv4 E6 Pen Pen (0)") LVDS1
nitrogen --head=0 ~/.config/backgrounds/current/ --random --set-auto 
nitrogen --head=1 ~/.config/backgrounds/current/ --random --set-auto 
sleep 2;
killall polybar
launch_polybar.sh
