#!/bin/zsh
# A fuzzy file-finder and opener based on dmenu 
# Requires: dmenu, xdg-utils 
# To be used as a custom rofi mode. Example: rofi -show :rofind -modi :rofind
if [ -z "$@" ]; then
	fd --hidden 2> /dev/null
else
	case "$(echo $@ | cut -d " " -f 1)" in
		a)
			exec $BROWSER https://wiki.archlinux.org/index.php/"$(echo $@ | cut -d " " -f2-)" &> /dev/null &
			;;
		w)
			exec $BROWSER https://en.wikipedia.org/wiki/"$(echo $@ | cut -d " " -f2-)" &> /dev/null &
			;;
		*)
			exec xdg-open "$(echo $@)" &> /dev/null &
			;;
	esac
fi
